### ISSUE TITLE
This is an issue to store images for the README

### ISSUE THREAD

**Issue by quickshiftin** [quickshiftin/mage2-bug-6803#1]
<img width="183" alt="no-media-attrs-after-programatic-load" src="https://cloud.githubusercontent.com/assets/96733/24435944/903f8cca-13f5-11e7-81fa-43c86351ca01.png">

<img width="1027" alt="image-attrs-after-programmatic-load" src="https://cloud.githubusercontent.com/assets/96733/24435945/92b76d60-13f5-11e7-809b-eae23050ddcd.png">

<img width="187" alt="media-attrs-after-manual-update" src="https://cloud.githubusercontent.com/assets/96733/24435948/955d9f94-13f5-11e7-9d8f-e93ef17358d6.png">

<img width="1038" alt="media-attrs-set-2" src="https://cloud.githubusercontent.com/assets/96733/24436269/d71a84c2-13f7-11e7-8dd8-8e91da86ee62.png">

**Comment by danyvega1990** [comment]
I'm getting this same issue, did you find any fix??

**Comment by quickshiftin** [comment]
Hi @danyvega1990, I never did get to the bottom of this. In the M2 project I was working on the catalog was small enough where I was able to deal with the problem manually.

It's shocking that this issue is still prevalent in M2. I think the main issue is Magento is too big for its own good. Really slow release cycles and too much dependency on the core team to oversee the enormous product.

**Comment by danyvega1990** [comment]
Today I tested the problem using the 2.1.8 version of magento and the problem it's solved. Thanks anyway for everything

**Comment by quickshiftin** [comment]
That's great to hear! Thank you for letting me know.
